using System.Diagnostics; using System.Windows; using System.Windows.Controls; using System.Windows.Input; using Microsoft.Win32; using BookmarkModel=JASS.Bookmark.Master.Models.Bookmark; using JASS.Bookmark.Master.Models; using JASS.Bookmark.Master.Services;
namespace JASS.Bookmark.Master;
public partial class MainWindow:Window
{
 readonly BookmarkDbService db=new(); readonly BookmarkImportExportService io=new(); List<BookmarkModel> all=new(); string page="Dashboard"; BookmarkModel? selected;
 public MainWindow(){InitializeComponent();Load();}
 void Load(){all=db.GetAll();Render();}
 void Render(){var s=db.Stats();PageTitle.Text=page switch{"Dashboard"=>"Resource Library Dashboard","All"=>"All Resources","Favorites"=>"Favorites","ReadLater"=>"Read Later","Types"=>"Resource Types","Folders"=>"Folder Manager","Tags"=>"Tag Manager","Collections"=>"Collections","Duplicates"=>"Duplicate Candidates","Broken"=>"Broken Links",_=>"Resource Library"};IEnumerable<BookmarkModel> q=all;var term=SearchBox.Text.Trim();if(term.Length>0)q=q.Where(b=>$"{b.Title} {b.Url} {b.ResourceType} {b.Folder} {b.Tags} {b.Description} {b.Notes}".Contains(term,StringComparison.OrdinalIgnoreCase));q=page switch{"Favorites"=>q.Where(b=>b.Favorite),"ReadLater"=>q.Where(b=>b.ReadLater),"Broken"=>q.Where(b=>b.Broken),"Types"=>q.OrderBy(b=>b.ResourceType).ThenBy(b=>b.Title),"Folders"=>q.OrderBy(b=>b.Folder).ThenBy(b=>b.Title),"Tags"=>q.OrderBy(b=>b.Tags).ThenBy(b=>b.Title),"Duplicates"=>q.Where((b,i)=>all.FindIndex(x=>x.Url.Equals(b.Url,StringComparison.OrdinalIgnoreCase))!=i),_=>q};GridBookmarks.ItemsSource=q.ToList();UpdateDetails();if(page=="Dashboard")ShowDashboard(s);else if(page=="Collections")ShowCollections();else if(page=="Types"||page=="Folders"||page=="Tags"||page=="Duplicates"||page=="Broken")ShowInfo(page,s);else if(page=="Local")ShowLocal();else ShowLibrary();}
 void ShowLibrary(){LibraryWorkspace.Visibility=Visibility.Visible;}
 void ShowLocal(){LibraryWorkspace.Visibility=Visibility.Collapsed;var w=new LocalResources();MainContentOverlay(w);}
 void MainContentOverlay(FrameworkElement content){if(content is null)return;var host=new Window{Owner=this,Content=content,Title="Local Resources",Width=1200,Height=760,Background=System.Windows.Media.Brushes.White};host.ShowDialog();page="Dashboard";SearchBox.Clear();Load();}
 void ShowDashboard(BookmarkStats s){LibraryWorkspace.Visibility=Visibility.Visible;GridBookmarks.Visibility=Visibility.Visible;var types=all.GroupBy(x=>x.ResourceType).OrderByDescending(g=>g.Count()).Take(8).Select(g=>$"{g.Key}: {g.Count()}");DetailTitle.Text="Resource Library";DetailType.Text="v1.2 Resource Library";DetailUrl.Text=$"{s.Total:N0} resources • {s.Folders:N0} folders • {all.SelectMany(x=>x.Tags.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries)).Distinct(StringComparer.OrdinalIgnoreCase).Count():N0} tags";DetailFolder.Text="Resource types";DetailTags.Text=string.Join("\n",types);DetailDescription.Text="Use folders for hierarchy, tags for cross-cutting subjects, and collections for research projects.";DetailNotes.Text="Double-click a resource or use Edit to maintain its metadata.";DetailMeta.Text=$"Favorites: {s.Favorites}   Read Later: {s.ReadLater}   Broken: {s.Broken}   Domains: {s.Domains}";}
 void ShowInfo(string p,BookmarkStats s){LibraryWorkspace.Visibility=Visibility.Visible;GridBookmarks.Visibility=Visibility.Visible;DetailTitle.Text=p switch{"Types"=>"Resource Types","Folders"=>"Folder Manager","Tags"=>"Tag Manager","Duplicates"=>"Duplicate Candidates","Broken"=>"Broken Links",_=>p};DetailType.Text=p switch{"Types"=>"Classify every resource","Folders"=>"Use / to create hierarchy","Tags"=>"Cross-cutting organization","Duplicates"=>"Review before cleanup","Broken"=>"Keep until repaired or archived",_=>""};var groups=p switch{"Types"=>all.GroupBy(x=>x.ResourceType).OrderBy(x=>x.Key).Select(x=>$"{x.Key}  •  {x.Count()}"),"Folders"=>all.GroupBy(x=>x.Folder).OrderBy(x=>x.Key).Select(x=>$"{x.Key}  •  {x.Count()}"),"Tags"=>all.SelectMany(x=>x.Tags.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries)).GroupBy(x=>x,StringComparer.OrdinalIgnoreCase).OrderBy(x=>x.Key).Select(x=>$"{x.Key}  •  {x.Count()}"),"Duplicates"=>all.GroupBy(x=>x.Url,StringComparer.OrdinalIgnoreCase).Where(x=>x.Count()>1).Select(x=>$"{x.Key}  •  {x.Count()} copies"),"Broken"=>all.Where(x=>x.Broken).Select(x=>$"{x.Title}  •  {x.Url}"),_=>Array.Empty<string>()};DetailUrl.Text=string.Join("\n",groups.Take(30));DetailFolder.Text=p=="Folders"?"Hierarchy example: AI/Models, AI/Research, Python/Docs":"";DetailTags.Text=p=="Tags"?"Use comma-separated tags on each resource and search them globally.":"";DetailDescription.Text=p=="Duplicates"?"Duplicate candidates are grouped by exact URL so you can review them safely.":p=="Broken"?"Broken flags are manual in v1.2; they remain in the master library until you decide what to do.":"";DetailNotes.Text=p=="Types"?"Use the Edit button to change a resource type.":"";DetailMeta.Text=$"Total resources: {all.Count}";}
 void ShowCollections(){LibraryWorkspace.Visibility=Visibility.Visible;GridBookmarks.Visibility=Visibility.Visible;var cols=db.GetCollections();DetailTitle.Text="Research Collections";DetailType.Text="Group resources without moving them";DetailUrl.Text=string.Join("\n",cols.Select(c=>$"{c.Name}  •  {c.ResourceCount} resources"));DetailFolder.Text="Create collections with the + Collection button below.";DetailTags.Text="Collections are separate from folders and tags.";DetailDescription.Text="Examples: Privacy Research, Python Learning, Athena Research, Alberta Driving.";DetailNotes.Text="Use a collection for a project or research theme while keeping the resource in its original folder.";DetailMeta.Text=$"Collections: {cols.Count}";}
 void UpdateDetails(){selected=GridBookmarks.SelectedItem as BookmarkModel;if(selected==null)return;DetailTitle.Text=selected.Title;DetailType.Text=selected.ResourceType;DetailUrl.Text=selected.Url;DetailFolder.Text=selected.Folder;DetailTags.Text=string.IsNullOrWhiteSpace(selected.Tags)?"—":selected.Tags;DetailDescription.Text=string.IsNullOrWhiteSpace(selected.Description)?"—":selected.Description;DetailNotes.Text=string.IsNullOrWhiteSpace(selected.Notes)?"—":selected.Notes;DetailMeta.Text=$"Added: {selected.DateAdded}\nSource: {selected.Source}\nFavorite: {(selected.Favorite?"Yes":"No")}   Read Later: {(selected.ReadLater?"Yes":"No")}";}
 void Nav_Click(object sender,RoutedEventArgs e){page=(string)((Button)sender).Tag;SearchBox.Clear();GridBookmarks.Visibility=Visibility.Visible;Load();}
 void Search_TextChanged(object s,TextChangedEventArgs e){if(IsLoaded)Render();} void Grid_SelectionChanged(object s,SelectionChangedEventArgs e){UpdateDetails();}
 void Grid_DoubleClick(object s,MouseButtonEventArgs e){OpenSelected_Click(s,e);}
 void OpenSelected_Click(object s,RoutedEventArgs e){if(selected==null)return;try{Process.Start(new ProcessStartInfo(selected.Url){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"Open Resource",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 void EditSelected_Click(object s,RoutedEventArgs e){if(selected==null){MessageBox.Show("Select a resource first.");return;}var copy=Clone(selected);var d=new BookmarkEditor(copy);if(d.ShowDialog()==true){db.Update(d.Bookmark);Load();}}
 void DeleteSelected_Click(object s,RoutedEventArgs e){if(selected==null)return;if(MessageBox.Show($"Delete '{selected.Title}' from the master library?","Delete Resource",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;db.Delete(selected.Id);selected=null;Load();}
 static BookmarkModel Clone(BookmarkModel b)=>new(){Id=b.Id,Title=b.Title,Url=b.Url,Folder=b.Folder,Tags=b.Tags,Notes=b.Notes,Description=b.Description,Source=b.Source,ResourceType=b.ResourceType,DateAdded=b.DateAdded,LastVisited=b.LastVisited,Favorite=b.Favorite,ReadLater=b.ReadLater,Archived=b.Archived,Broken=b.Broken};
 void Favorite_Click(object s,RoutedEventArgs e){ToggleFlag(s,"favorite",e);}void ReadLater_Click(object s,RoutedEventArgs e){ToggleFlag(s,"later",e);}void Broken_Click(object s,RoutedEventArgs e){ToggleFlag(s,"broken",e);}void ToggleFlag(object sender,string flag,RoutedEventArgs e){if(sender is CheckBox cb&&cb.DataContext is BookmarkModel b){if(flag=="favorite")b.Favorite=cb.IsChecked==true;else if(flag=="later")b.ReadLater=cb.IsChecked==true;else b.Broken=cb.IsChecked==true;db.Update(b);all=db.GetAll();Render();e.Handled=true;}}
 void NewCollection_Click(object s,RoutedEventArgs e){var d=new CollectionEditor();if(d.ShowDialog()!=true)return;try{db.AddCollection(d.CollectionName,d.Description);page="Collections";Load();}catch(Exception ex){MessageBox.Show($"Could not create collection.\n\n{ex.Message}","Collections",MessageBoxButton.OK,MessageBoxImage.Warning);}}
 void AddToCollection_Click(object s,RoutedEventArgs e){if(selected==null){MessageBox.Show("Select a resource first.");return;}var cols=db.GetCollections();if(cols.Count==0){MessageBox.Show("Create a collection first using + Collection.");return;}var pick=new Window{Owner=this,Title="Add Resource to Collection",Width=460,Height=320,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=System.Windows.Media.Brushes.White};var panel=new StackPanel{Margin=new Thickness(22)};panel.Children.Add(new TextBlock{Text="Choose a collection",FontSize=20,FontWeight=FontWeights.Bold,Margin=new Thickness(0,0,0,14)});var combo=new ComboBox{ItemsSource=cols,DisplayMemberPath="Name",Height=34};panel.Children.Add(combo);var ok=new Button{Content="Add Resource",Background=System.Windows.Media.Brushes.DodgerBlue,Foreground=System.Windows.Media.Brushes.White,Margin=new Thickness(0,18,0,0),Padding=new Thickness(14,7,14,7)};ok.Click+=(a,b)=>{if(combo.SelectedItem is ResourceCollection c){db.AddToCollection(c.Id,selected.Id);pick.DialogResult=true;pick.Close();}};panel.Children.Add(ok);pick.Content=panel;pick.ShowDialog();if(page=="Collections")Render();}
 void Add_Click(object s,RoutedEventArgs e){var d=new BookmarkEditor();if(d.ShowDialog()==true){if(db.Add(d.Bookmark))Load();else MessageBox.Show("This URL already exists in the master library.","Resource Library",MessageBoxButton.OK,MessageBoxImage.Information);}}
 void Import_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Bookmark files|*.html;*.htm;*.json|HTML bookmarks|*.html;*.htm|JSON master|*.json"};if(d.ShowDialog()!=true)return;var items=d.FileName.EndsWith(".json",StringComparison.OrdinalIgnoreCase)?io.ImportJson(d.FileName):io.ImportHtml(d.FileName,System.IO.Path.GetFileNameWithoutExtension(d.FileName));int n=0;foreach(var b in items){if(string.IsNullOrWhiteSpace(b.ResourceType))b.ResourceType="Web Page";if(db.Add(b))n++;}Load();MessageBox.Show($"Imported {n:N0} new resources. Existing URLs were skipped.","Import complete",MessageBoxButton.OK,MessageBoxImage.Information);}
 void Export_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="HTML bookmark file|*.html|JSON master file|*.json",FileName="JASS-Bookmark-Master"};if(d.ShowDialog()!=true)return;if(d.FileName.EndsWith(".json",StringComparison.OrdinalIgnoreCase))io.ExportJson(d.FileName,all);else io.ExportHtml(d.FileName,all);}
 void Backup_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="JSON master backup|*.json",FileName=$"JASS-Bookmark-Master-{DateTime.Now:yyyyMMdd-HHmm}.json"};if(d.ShowDialog()==true)io.ExportJson(d.FileName,all);}
}
