using System.Diagnostics; using System.Windows; using System.Windows.Controls; using System.Windows.Controls.Primitives; using System.Windows.Input; using Microsoft.Win32; using BookmarkModel = JASS.Bookmark.Master.Models.Bookmark;
using JASS.Bookmark.Master.Models; using JASS.Bookmark.Master.Services;
namespace JASS.Bookmark.Master;
public partial class MainWindow:Window
{
 readonly BookmarkDbService db=new(); readonly BookmarkImportExportService io=new(); List<BookmarkModel> all=new(); string page="Dashboard";
 public MainWindow(){InitializeComponent();Load();}
 void Load(){all=db.GetAll();Render();}
 void Render(){var s=db.Stats();PageTitle.Text=page switch{"Local"=>"Local Resources","All"=>"All Bookmarks","Favorites"=>"Favorites","ReadLater"=>"Read Later","Folders"=>"Folders","Tags"=>"Tags","Duplicates"=>"Duplicate Candidates","Broken"=>"Broken Links",_=>"Bookmark Dashboard"}; IEnumerable<BookmarkModel> q=all; var term=SearchBox.Text.Trim();if(term.Length>0)q=q.Where(b=>$"{b.Title} {b.Url} {b.Folder} {b.Tags} {b.Notes}".Contains(term,StringComparison.OrdinalIgnoreCase));q=page switch{"Favorites"=>q.Where(b=>b.Favorite),"ReadLater"=>q.Where(b=>b.ReadLater),"Broken"=>q.Where(b=>b.Broken),"Folders"=>q.OrderBy(b=>b.Folder).ThenBy(b=>b.Title),_=>q};GridBookmarks.ItemsSource=q.ToList();if(page=="Dashboard")MainContent.Content=Dashboard(s);else if(page=="Local")MainContent.Content=new LocalResources();else MainContent.Content=Info(page,s);}
 FrameworkElement Dashboard(BookmarkStats s){var p=new StackPanel();p.Children.Add(new TextBlock{Text="Your bookmark library",FontSize=28,FontWeight=FontWeights.Bold,Foreground=System.Windows.Media.Brushes.DarkSlateGray});p.Children.Add(new TextBlock{Text="Bring Chrome, Edge, Firefox and other bookmark sources into one master collection. Search it, tag it, annotate it, deduplicate it and export it whenever you need.",Foreground=System.Windows.Media.Brushes.SlateGray,Margin=new Thickness(0,5,0,18),TextWrapping=TextWrapping.Wrap});var g=new UniformGrid{Columns=5};foreach(var x in new[]{($"{s.Total}","Bookmarks"),($"{s.Favorites}","Favorites"),($"{s.ReadLater}","Read Later"),($"{s.Folders}","Folders"),($"{s.Broken}","Broken")}){var b=new Border{Background=System.Windows.Media.Brushes.White,BorderBrush=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(220,229,238)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(10),Margin=new Thickness(4),Padding=new Thickness(15)};var st=new StackPanel();st.Children.Add(new TextBlock{Text=x.Item1,FontSize=25,FontWeight=FontWeights.Bold,Foreground=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(37,99,235))});st.Children.Add(new TextBlock{Text=x.Item2,Foreground=System.Windows.Media.Brushes.SlateGray});b.Child=st;g.Children.Add(b);}p.Children.Add(g);return new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};}
 FrameworkElement Info(string p,BookmarkStats s){return new Border{Background=System.Windows.Media.Brushes.White,Padding=new Thickness(18),Child=new TextBlock{Text=p switch{"Duplicates"=>"Duplicate candidates are identified by matching URLs. Use this view before cleanup or export.","Folders"=>"Use folders for broad organization; use tags for cross-cutting topics.","Tags"=>"Tags let one bookmark belong to multiple subjects without duplicating the bookmark.","Broken"=>"Links marked broken are kept in the master library until you decide whether to repair, archive or delete them.",_=>"Select a bookmark to inspect or double-click it to open it in your default browser."},TextWrapping=TextWrapping.Wrap,Foreground=System.Windows.Media.Brushes.SlateGray}};}
 void Nav_Click(object sender,RoutedEventArgs e){page=(string)((Button)sender).Tag;bool local=page=="Local";GridBookmarks.Visibility=local?Visibility.Collapsed:Visibility.Visible;MainContent.SetValue(Grid.RowSpanProperty, local?2:1);Render();}
 void Search_TextChanged(object s,TextChangedEventArgs e){if(IsLoaded)Render();}
 void Add_Click(object s,RoutedEventArgs e){var d=new BookmarkEditor();if(d.ShowDialog()==true){if(db.Add(d.Bookmark))Load();else MessageBox.Show("This URL already exists in the master library.","Bookmark Master",MessageBoxButton.OK,MessageBoxImage.Information);}}
 void Grid_DoubleClick(object s,MouseButtonEventArgs e){if(GridBookmarks.SelectedItem is BookmarkModel b && Uri.TryCreate(b.Url,UriKind.Absolute,out var u))Process.Start(new ProcessStartInfo(u.ToString()){UseShellExecute=true});}
 void Grid_SelectionChanged(object s,SelectionChangedEventArgs e){ }
 void Favorite_Click(object s,RoutedEventArgs e){ToggleFlag(s, e, "favorite");}
 void ReadLater_Click(object s,RoutedEventArgs e){ToggleFlag(s, e, "later");}
 void Broken_Click(object s,RoutedEventArgs e){ToggleFlag(s, e, "broken");}
 void ToggleFlag(object sender, RoutedEventArgs e, string flag){if(sender is CheckBox cb && cb.DataContext is BookmarkModel b){bool value=cb.IsChecked==true;if(flag=="favorite")b.Favorite=value;else if(flag=="later")b.ReadLater=value;else b.Broken=value;db.Update(b);all=db.GetAll();Render();e.Handled=true;}}
 void Import_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Bookmark files|*.html;*.htm;*.json|HTML bookmarks|*.html;*.htm|JSON master|*.json"};if(d.ShowDialog()!=true)return;var items=d.FileName.EndsWith(".json",StringComparison.OrdinalIgnoreCase)?io.ImportJson(d.FileName):io.ImportHtml(d.FileName,System.IO.Path.GetFileNameWithoutExtension(d.FileName));int n=0;foreach(var b in items){if(db.Add(b))n++;}Load();MessageBox.Show($"Imported {n} new bookmarks. Existing URLs were skipped.","Import complete",MessageBoxButton.OK,MessageBoxImage.Information);}
 void Export_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="HTML bookmark file|*.html|JSON master file|*.json",FileName="JASS-Bookmark-Master"};if(d.ShowDialog()!=true)return;if(d.FileName.EndsWith(".json",StringComparison.OrdinalIgnoreCase))io.ExportJson(d.FileName,all);else io.ExportHtml(d.FileName,all);}
 void Backup_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="JSON master backup|*.json",FileName=$"JASS-Bookmark-Master-{DateTime.Now:yyyyMMdd-HHmm}.json"};if(d.ShowDialog()==true)io.ExportJson(d.FileName,all);}
}
